/**
 * pdfReport.js – Generate a professional forensic evidence PDF report.
 *
 * Exports:
 *   generateEvidenceReport(scan) → Promise<Buffer>
 */

const PDFDocument = require('pdfkit');

// ─── Color palette ────────────────────────────────────────────────────────────

const VERDICT_COLORS = {
  AI_GENERATED: '#ff3355',
  AUTHENTIC:    '#00cc66',
  UNCERTAIN:    '#ffaa00',
};

const SEVERITY_COLORS = {
  CRITICAL: '#ff3355',
  WARNING:  '#ffaa00',
  NOTE:     '#004466',
  CLEAR:    '#00cc66',
};

const VERDICT_LABELS = {
  AI_GENERATED: 'AI-GENERATED CONTENT DETECTED',
  AUTHENTIC:    'LIKELY AUTHENTIC',
  UNCERTAIN:    'INCONCLUSIVE ANALYSIS',
};

const VERDICT_ICONS = {
  AI_GENERATED: '!',
  AUTHENTIC:    '\u2713',
  UNCERTAIN:    '?',
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

function hexToRGB(hex) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return [r, g, b];
}

function formatDate(dateStr) {
  if (!dateStr) return 'Unknown';
  const d = new Date(dateStr);
  return d.toLocaleString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
    hour: '2-digit', minute: '2-digit', timeZoneName: 'short'
  });
}

// ─── Main generator ───────────────────────────────────────────────────────────

function generateEvidenceReport(scan) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margin: 60,
      bufferPages: true,
      info: {
        Title: 'VeritasAI Forensic Report — ' + scan.id,
        Author: 'VeritasAI',
        Subject: 'AI-Generated Media Forensic Analysis',
      }
    });

    const chunks = [];
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const verdict = scan.verdict || 'UNCERTAIN';
    const verdictColor = VERDICT_COLORS[verdict] || VERDICT_COLORS.UNCERTAIN;

    // ───────────────────────────────────────────────────────────────────────
    // HEADER BAND
    // ───────────────────────────────────────────────────────────────────────

    doc.save();
    doc.rect(0, 0, doc.page.width, 80).fill(verdictColor);

    // Left side — branding
    doc.font('Helvetica-Bold').fontSize(22).fillColor('#ffffff');
    doc.text('VERITASAI', 30, 18, { lineBreak: false });
    doc.font('Helvetica').fontSize(10).fillColor('#ffffff');
    doc.text('AI-GENERATED MEDIA FORENSIC REPORT', 30, 46, { lineBreak: false });

    // Right side — verdict label
    const verdictLabel = (VERDICT_ICONS[verdict] || '?') + ' ' + (VERDICT_LABELS[verdict] || 'UNKNOWN');
    doc.font('Helvetica-Bold').fontSize(12).fillColor('#ffffff');
    doc.text(verdictLabel, 300, 22, { width: 220, align: 'right', lineBreak: false });

    // Far right — confidence
    const confStr = (scan.confidence || 0) + '%';
    doc.font('Helvetica-Bold').fontSize(32).fillColor('#ffffff');
    doc.text(confStr, doc.page.width - 120, 22, { width: 90, align: 'right', lineBreak: false });

    doc.restore();

    // ───────────────────────────────────────────────────────────────────────
    // DISCLAIMER
    // ───────────────────────────────────────────────────────────────────────

    doc.y = 95;
    const disclaimerY = doc.y;
    doc.save();
    doc.rect(doc.page.margins.left, disclaimerY, pageWidth, 40)
       .fill('#1a1f2e');
    doc.font('Helvetica').fontSize(7).fillColor('#888888');
    doc.text(
      'This report is generated by VeritasAI automated forensic analysis and is intended as supporting evidence only. ' +
      'Results are probabilistic, not definitive. Always verify findings with additional sources before taking legal action. ' +
      'VeritasAI (veritasai-g2u6.onrender.com)',
      doc.page.margins.left + 10, disclaimerY + 8,
      { width: pageWidth - 20 }
    );
    doc.restore();
    doc.y = disclaimerY + 50;

    // ───────────────────────────────────────────────────────────────────────
    // SECTION HEADING helper
    // ───────────────────────────────────────────────────────────────────────

    function sectionHeading(title) {
      doc.moveDown(0.8);
      doc.font('Helvetica-Bold').fontSize(10).fillColor('#00d4ff');
      doc.text(title);
      const lineY = doc.y + 2;
      doc.save();
      doc.moveTo(doc.page.margins.left, lineY)
         .lineTo(doc.page.margins.left + pageWidth, lineY)
         .strokeColor('#00d4ff').lineWidth(0.5).stroke();
      doc.restore();
      doc.y = lineY + 8;
    }

    // ───────────────────────────────────────────────────────────────────────
    // SCAN METADATA
    // ───────────────────────────────────────────────────────────────────────

    sectionHeading('SCAN INFORMATION');

    const metaLeft = [
      ['Scan ID',      scan.id || 'N/A'],
      ['Date',         formatDate(scan.created_at)],
      ['Media Type',   (scan.media_type || 'image').charAt(0).toUpperCase() + (scan.media_type || 'image').slice(1)],
      ['Input Method', (scan.input_type || 'url').charAt(0).toUpperCase() + (scan.input_type || 'url').slice(1)],
    ];

    const metaRight = [
      ['Verdict',         verdict],
      ['Confidence',      (scan.confidence || 0) + '%'],
      ['Suspected Model', scan.suspected_model || 'Not determined'],
      ['Platform',        'VeritasAI v1.0'],
    ];

    const metaStartY = doc.y;
    const colWidth = pageWidth / 2;

    metaLeft.forEach(([label, value], i) => {
      const rowY = metaStartY + i * 16;
      doc.font('Helvetica-Bold').fontSize(9).fillColor('#888888');
      doc.text(label + ':', doc.page.margins.left, rowY, { width: 90, lineBreak: false });
      const isId = label === 'Scan ID';
      doc.font(isId ? 'Courier' : 'Helvetica').fontSize(9).fillColor('#cccccc');
      doc.text(value, doc.page.margins.left + 92, rowY, { width: colWidth - 92, lineBreak: false });
    });

    metaRight.forEach(([label, value], i) => {
      const rowY = metaStartY + i * 16;
      const xOffset = doc.page.margins.left + colWidth + 10;
      doc.font('Helvetica-Bold').fontSize(9).fillColor('#888888');
      doc.text(label + ':', xOffset, rowY, { width: 100, lineBreak: false });
      const isVerdict = label === 'Verdict';
      doc.font('Helvetica-Bold').fontSize(9)
         .fillColor(isVerdict ? verdictColor : '#cccccc');
      doc.text(value, xOffset + 102, rowY, { width: colWidth - 112, lineBreak: false });
    });

    doc.y = metaStartY + metaLeft.length * 16 + 4;

    // ───────────────────────────────────────────────────────────────────────
    // ANALYSIS SUMMARY
    // ───────────────────────────────────────────────────────────────────────

    sectionHeading('ANALYSIS SUMMARY');
    doc.font('Helvetica').fontSize(10).fillColor('#cccccc');
    doc.text(scan.summary || 'No summary available.', {
      width: pageWidth, lineGap: 3
    });

    // ───────────────────────────────────────────────────────────────────────
    // FORENSIC SIGNALS
    // ───────────────────────────────────────────────────────────────────────

    sectionHeading('FORENSIC SIGNALS DETECTED');
    doc.font('Helvetica').fontSize(8).fillColor('#888888');
    doc.text('The following signals were identified during analysis:', { width: pageWidth });
    doc.moveDown(0.5);

    const signals = scan.signals || [];
    signals.forEach(signal => {
      const sevColor = SEVERITY_COLORS[signal.severity] || '#004466';

      // Check if we need a new page (leave 80px for footer + content)
      if (doc.y > doc.page.height - 120) {
        doc.addPage();
        doc.y = doc.page.margins.top;
      }

      const blockY = doc.y;

      // Colored left bar
      doc.save();
      doc.rect(doc.page.margins.left, blockY, 4, 40).fill(sevColor);
      doc.restore();

      // Signal name
      doc.font('Helvetica-Bold').fontSize(11).fillColor('#dddddd');
      doc.text(signal.name || 'Unknown Signal', doc.page.margins.left + 12, blockY, {
        width: pageWidth - 100, lineBreak: false
      });

      // Severity badge
      doc.font('Helvetica-Bold').fontSize(9).fillColor(sevColor);
      doc.text('[' + (signal.severity || 'NOTE') + ']', doc.page.margins.left + pageWidth - 80, blockY, {
        width: 80, align: 'right', lineBreak: false
      });

      // Description
      doc.font('Helvetica').fontSize(9).fillColor('#aaaaaa');
      doc.text(signal.technical_description || '', doc.page.margins.left + 12, blockY + 16, {
        width: pageWidth - 16, lineGap: 2
      });

      doc.y = Math.max(doc.y, blockY + 40) + 8;
    });

    // ───────────────────────────────────────────────────────────────────────
    // EDUCATION SECTION
    // ───────────────────────────────────────────────────────────────────────

    const exp = scan.explanation || {};

    if (exp.how_detected || exp.what_to_look_for || exp.technology_note) {
      // Page break check
      if (doc.y > doc.page.height - 200) {
        doc.addPage();
        doc.y = doc.page.margins.top;
      }

      sectionHeading('UNDERSTANDING THIS RESULT');

      if (exp.how_detected) {
        doc.font('Helvetica-Bold').fontSize(10).fillColor('#dddddd');
        doc.text('How It Was Detected');
        doc.moveDown(0.3);
        doc.font('Helvetica').fontSize(9).fillColor('#aaaaaa');
        doc.text(exp.how_detected, { width: pageWidth, lineGap: 2 });
        doc.moveDown(0.6);
      }

      if (exp.what_to_look_for) {
        if (doc.y > doc.page.height - 120) { doc.addPage(); doc.y = doc.page.margins.top; }
        doc.font('Helvetica-Bold').fontSize(10).fillColor('#dddddd');
        doc.text('What To Look For Yourself');
        doc.moveDown(0.3);
        doc.font('Helvetica').fontSize(9).fillColor('#aaaaaa');
        doc.text(exp.what_to_look_for, { width: pageWidth, lineGap: 2 });
        doc.moveDown(0.6);
      }

      if (exp.technology_note) {
        if (doc.y > doc.page.height - 120) { doc.addPage(); doc.y = doc.page.margins.top; }
        doc.font('Helvetica-Bold').fontSize(10).fillColor('#dddddd');
        doc.text('About The Technology');
        doc.moveDown(0.3);
        doc.font('Helvetica').fontSize(9).fillColor('#aaaaaa');
        doc.text(exp.technology_note, { width: pageWidth, lineGap: 2 });
      }
    }

    // ───────────────────────────────────────────────────────────────────────
    // FOOTER on every page
    // ───────────────────────────────────────────────────────────────────────

    const totalPages = doc.bufferedPageRange().count;
    for (let i = 0; i < totalPages; i++) {
      doc.switchToPage(i);
      const footerY = doc.page.height - 40;

      // Thin line
      doc.save();
      doc.moveTo(doc.page.margins.left, footerY)
         .lineTo(doc.page.margins.left + pageWidth, footerY)
         .strokeColor('#333333').lineWidth(0.5).stroke();
      doc.restore();

      // Left: scan ID
      doc.font('Courier').fontSize(7).fillColor('#666666');
      doc.text(
        'VeritasAI Forensic Report  —  Scan ID: ' + (scan.id || 'N/A'),
        doc.page.margins.left, footerY + 6,
        { width: pageWidth - 80, lineBreak: false }
      );

      // Right: page number
      doc.font('Helvetica').fontSize(7).fillColor('#666666');
      doc.text(
        'Page ' + (i + 1) + ' of ' + totalPages,
        doc.page.margins.left, footerY + 6,
        { width: pageWidth, align: 'right', lineBreak: false }
      );
    }

    doc.end();
  });
}

module.exports = { generateEvidenceReport };
